import { RoundConfig } from '../engine/types'

export const HANTALAPAY_ROUNDS: RoundConfig[] = [
  {
    roundNumber: 1,
    titleKz: 'Балақай Бастауы',
    asykCount: 12,
    hasKhan: true,
    khanHiddenDelayMs: 0,
    timeLimitSec: 20,
    scatterForceMin: 180,
    scatterForceMax: 320,
    obstacleCount: 0,
    targetScoreFor3Stars: 1500,
    targetScoreFor2Stars: 1000,
    targetScoreFor1Star: 600,
    carpetBgVariant: 'red-tekemet',
  },
  {
    roundNumber: 2,
    titleKz: 'Дала Ырғағы',
    asykCount: 15,
    hasKhan: true,
    khanHiddenDelayMs: 0,
    timeLimitSec: 18,
    scatterForceMin: 220,
    scatterForceMax: 380,
    obstacleCount: 0,
    targetScoreFor3Stars: 2000,
    targetScoreFor2Stars: 1400,
    targetScoreFor1Star: 900,
    carpetBgVariant: 'red-tekemet',
  },
  {
    roundNumber: 3,
    titleKz: 'Шебер Түсуі',
    asykCount: 18,
    hasKhan: true,
    khanHiddenDelayMs: 200,
    timeLimitSec: 16,
    scatterForceMin: 250,
    scatterForceMax: 420,
    obstacleCount: 1,
    targetScoreFor3Stars: 2500,
    targetScoreFor2Stars: 1800,
    targetScoreFor1Star: 1200,
    carpetBgVariant: 'blue-syrmak',
  },
  {
    roundNumber: 4,
    titleKz: 'Шапшаң Қол',
    asykCount: 22,
    hasKhan: true,
    khanHiddenDelayMs: 400,
    timeLimitSec: 14,
    scatterForceMin: 280,
    scatterForceMax: 460,
    obstacleCount: 2,
    targetScoreFor3Stars: 3200,
    targetScoreFor2Stars: 2200,
    targetScoreFor1Star: 1500,
    carpetBgVariant: 'blue-syrmak',
  },
  {
    roundNumber: 5,
    titleKz: 'Ханның Ғажайыбы',
    asykCount: 26,
    hasKhan: true,
    khanHiddenDelayMs: 500,
    timeLimitSec: 12,
    scatterForceMin: 320,
    scatterForceMax: 500,
    obstacleCount: 2,
    targetScoreFor3Stars: 4000,
    targetScoreFor2Stars: 2800,
    targetScoreFor1Star: 1900,
    carpetBgVariant: 'gold-dastarkhan',
  },
  {
    roundNumber: 6,
    titleKz: 'Жүйрік Көз',
    asykCount: 30,
    hasKhan: true,
    khanHiddenDelayMs: 600,
    timeLimitSec: 11,
    scatterForceMin: 350,
    scatterForceMax: 540,
    obstacleCount: 3,
    targetScoreFor3Stars: 4800,
    targetScoreFor2Stars: 3400,
    targetScoreFor1Star: 2300,
    carpetBgVariant: 'gold-dastarkhan',
  },
  {
    roundNumber: 7,
    titleKz: 'Қошқар Мүйіз',
    asykCount: 34,
    hasKhan: true,
    khanHiddenDelayMs: 700,
    timeLimitSec: 10,
    scatterForceMin: 380,
    scatterForceMax: 580,
    obstacleCount: 3,
    targetScoreFor3Stars: 5600,
    targetScoreFor2Stars: 4000,
    targetScoreFor1Star: 2800,
    carpetBgVariant: 'red-tekemet',
  },
  {
    roundNumber: 8,
    titleKz: 'Батыр Лек',
    asykCount: 38,
    hasKhan: true,
    khanHiddenDelayMs: 800,
    timeLimitSec: 9,
    scatterForceMin: 400,
    scatterForceMax: 620,
    obstacleCount: 4,
    targetScoreFor3Stars: 6400,
    targetScoreFor2Stars: 4600,
    targetScoreFor1Star: 3300,
    carpetBgVariant: 'blue-syrmak',
  },
  {
    roundNumber: 9,
    titleKz: 'Сыр Серпіні',
    asykCount: 42,
    hasKhan: true,
    khanHiddenDelayMs: 900,
    timeLimitSec: 8.5,
    scatterForceMin: 420,
    scatterForceMax: 650,
    obstacleCount: 4,
    targetScoreFor3Stars: 7200,
    targetScoreFor2Stars: 5200,
    targetScoreFor1Star: 3800,
    carpetBgVariant: 'gold-dastarkhan',
  },
  {
    roundNumber: 10,
    titleKz: 'ҰЛЫ ХАНТАЛАПАЙ',
    asykCount: 45,
    hasKhan: true,
    khanHiddenDelayMs: 1000,
    timeLimitSec: 8,
    scatterForceMin: 450,
    scatterForceMax: 700,
    obstacleCount: 5,
    targetScoreFor3Stars: 8500,
    targetScoreFor2Stars: 6000,
    targetScoreFor1Star: 4500,
    carpetBgVariant: 'gold-dastarkhan',
  },
]

export function getRoundConfig(roundNumber: number): RoundConfig {
  const index = Math.max(0, Math.min(HANTALAPAY_ROUNDS.length - 1, roundNumber - 1))
  return HANTALAPAY_ROUNDS[index]
}
